2024-11-26 11:44:48,065 - exec_batchAPI - INFO - ジョブステータス取得: failed
2024-11-26 11:44:48,065 - exec_batchAPI - ERROR - ジョブエラーの詳細: Errors(data=[BatchError(code='token_limit_exceeded', line=None, message='Enqueued token limit reached for gpt-4o-2024-11-20 in organization org-I1RzwRyPZjqKajv71LJjcHPF. Limit: 90,000 enqueued tokens. Please try again once some in_progress batches have been completed.', param=None)], object='list')
2024-11-26 11:44:48,065 - exec_batchAPI - ERROR - Batchオブジェクト: Batch(id='batch_6745091201d48190a190e3bb40ee852a', completion_window='24h', created_at=1732577554, endpoint='/v1/chat/completions', input_file_id='file-HHJtPXwgjeNkZvDDvJNWKa', object='batch', status='failed', cancelled_at=None, cancelling_at=None, completed_at=None, error_file_id=None, errors=Errors(data=[BatchError(code='token_limit_exceeded', line=None, message='Enqueued token limit reached for gpt-4o-2024-11-20 in organization org-I1RzwRyPZjqKajv71LJjcHPF. Limit: 90,000 enqueued tokens. Please try again once some in_progress batches have been completed.', param=None)], object='list'), expired_at=None, expires_at=1732663954, failed_at=1732577555, finalizing_at=None, in_progress_at=None, metadata=None, output_file_id=None, request_counts=BatchRequestCounts(completed=0, failed=0, total=0))
